### ISSUE TITLE
如何在云引擎上使用es6

### ISSUE THREAD

**Issue by fangjj** [leancloud/leanengine-todo-demo#3]
如何用es6改写这个项目

**Comment by aisk** [comment]
在 package.json 中增加

``` json
  "engines": {
    "node": "4.x"
  }
```

可以使用 node 4.x，支持大部分 ES6 的语法。

**Comment by fangjj** [comment]
好像不支持import，可以使用babel，先编译再运行吗？

**Comment by aisk** [comment]
目前 node 都没有原生支持 import 语法，只能用预编译的方式解决。用 babel 没有问题。

**Comment by fangjj** [comment]
使用babel+gulp+webpack吗？结合leancloud目录结构是什么样子的。这样的话应该怎么部署到云上面，希望官方给demo哈。

**Comment by aisk** [comment]
这里有个类似的 demo，可以参考：https://github.com/leancloud/LeanEngine-Full-Stack

**Comment by wangxiao** [comment]
上面那个稍旧，但思路基本一致，也可以参考 https://github.com/wangxiao/romantic

**Comment by fangjj** [comment]
好的。谢谢你们。
